apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-default
  namespace: demo
spec:
  replicas: 4  # Number of replicas
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      schedulerName: second-scheduler
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80

