apiVersion: v1
kind: ConfigMap
metadata:
  name: second-scheduler-config
  namespace: demo
data:
  second-scheduler-config.yaml: |
    apiVersion: kubescheduler.config.k8s.io/v1
    kind: KubeSchedulerConfiguration
    profiles:
      - schedulerName: second-scheduler
        plugins:
          score:
            enabled:
            - name: NodeResourcesFit
            disabled:
            - name: "*"
        pluginConfig:
          - name: NodeResourcesFit
            args:
              scoringStrategy:
                resources:
                  - name: cpu
                    weight: 1
                  - name: memory
                    weight: 1
                requestedToCapacityRatio:
                  shape:
                    - utilization: 0
                      score: 10
                    - utilization: 100
                      score: 0
                type: RequestedToCapacityRatio

